In [1]:
from numpy import *
import random

In [2]:
def floyd2(n, W, D, P):
    for k in range(n):
        for i in range(n):
            for j in range(n):
                if D[i,k] + D[k,j] < D[i,j]:
                    P[i,j] = int(k+1)
                    D[i,j] = D[i,k] + D[k,j]
def path(P,Q,R):
    q = int(Q-1)
    r = int(R-1)
    if P[q,r] != 0:
        path(P,Q,P[q,r])
        print('v',P[q,r])
        path(P,P[q,r],R)

In [22]:
n = 5
W = array([[0,1,inf,1,5],
           [9,0,3,2,inf],
           [inf,inf,0,4,inf],
           [inf,inf,2,0,3],
           [3,inf,inf,inf,0]])
D = array(W)
P = zeros((n,n),dtype = int64)

In [23]:
floyd2(n, W, D, P)

In [24]:
print(W)
print(D)
print(P)
path(P,5,3)

[[ 0.  1. inf  1.  5.]
 [ 9.  0.  3.  2. inf]
 [inf inf  0.  4. inf]
 [inf inf  2.  0.  3.]
 [ 3. inf inf inf  0.]]
[[ 0.  1.  3.  1.  4.]
 [ 8.  0.  3.  2.  5.]
 [10. 11.  0.  4.  7.]
 [ 6.  7.  2.  0.  3.]
 [ 3.  4.  6.  4.  0.]]
[[0 0 4 0 4]
 [5 0 0 0 4]
 [5 5 0 0 4]
 [5 5 0 0 0]
 [0 1 4 1 0]]
v 1
v 4


In [36]:
n = 5
random.seed(1)
W2 = zeros((n,n))
pool = list(range(1,10))
pool.append(inf)
weights = [1]*9+[9]
for i in range(n):
    for j in range(n):
        if i!=j:
            W2[i,j] = random.choices(pool,weights)[0]
D2 = array(W2)
P2 = zeros((n,n),dtype = int64)
floyd2(n,W2,D2,P2)
print(W2)
print(D2)
print(P2)
path(P2,2,4)

[[ 0.  3. inf inf  5.]
 [ 9.  0.  9. inf inf]
 [ 2.  1.  0. inf  8.]
 [inf  1.  9.  0. inf]
 [ 5. inf inf  1.  0.]]
[[ 0.  3. 12.  6.  5.]
 [ 9.  0.  9. 15. 14.]
 [ 2.  1.  0.  8.  7.]
 [10.  1.  9.  0. 15.]
 [ 5.  2. 10.  1.  0.]]
[[0 0 2 5 0]
 [0 0 0 5 1]
 [0 0 0 5 1]
 [2 0 0 0 2]
 [0 4 4 0 0]]
v 1
v 5
