In [20]:
import numpy as np

In [48]:
def obst(n,p,R):
    A = np.pad(np.diag(p),(1,0),mode='constant',constant_values=(0))
    A = np.array(list(A.ravel()) + [0]*(n+1)).reshape((n+2,n+1))
    R = np.pad(np.diag(np.arange(1,n+1)),(1,0),mode='constant',constant_values=(0))
    for diag in range(1,n):
        for i in range(1,n-diag+1):
            j = i+diag
            #print('diag=',diag,'i=',i,' j=',j)
            mlist = [A[i,k-1]+A[k+1,j] for k in range(i,j+1)]
            #print('min:',mlist)
            A[i,j] = min(mlist)+sum(p[i-1:j])
            #print('p:',p[i-1:j])
            #print('A[i,j]:',A[i,j])
            R[i,j] = i+np.argmin(mlist)
            #print('R[i,j]:',R[i,j])
            #print()
    print()
    print('array A')
    print(A,'\n')
    print('array R')
    print(R,'\n')
    return A[1,n]

In [49]:
n = 4
p = [3/8,3/8,1/8,1/8]
R = np.zeros((n+1,n+1))

In [50]:
print('minimum cost:',obst(n,p,R))


array A
[[0.    0.    0.    0.    0.   ]
 [0.    0.375 1.125 1.375 1.75 ]
 [0.    0.    0.375 0.625 1.   ]
 [0.    0.    0.    0.125 0.375]
 [0.    0.    0.    0.    0.125]
 [0.    0.    0.    0.    0.   ]] 

array R
[[0 0 0 0 0]
 [0 1 1 2 2]
 [0 0 2 2 2]
 [0 0 0 3 3]
 [0 0 0 0 4]] 

minimum cost: 1.75


In [51]:
n = 6
p = [2/16,1/16,3/16,2/16,5/16,3/16]
R = np.zeros((n+1,n+1))

In [52]:
print('minimum cost:',obst(n,p,R))


array A
[[0.     0.     0.     0.     0.     0.     0.    ]
 [0.     0.125  0.25   0.625  0.875  1.625  2.0625]
 [0.     0.     0.0625 0.3125 0.5625 1.25   1.625 ]
 [0.     0.     0.     0.1875 0.4375 1.0625 1.4375]
 [0.     0.     0.     0.     0.125  0.5625 0.9375]
 [0.     0.     0.     0.     0.     0.3125 0.6875]
 [0.     0.     0.     0.     0.     0.     0.1875]
 [0.     0.     0.     0.     0.     0.     0.    ]] 

array R
[[0 0 0 0 0 0 0]
 [0 1 1 3 3 3 5]
 [0 0 2 3 3 5 5]
 [0 0 0 3 3 5 5]
 [0 0 0 0 4 5 5]
 [0 0 0 0 0 5 5]
 [0 0 0 0 0 0 6]] 

minimum cost: 2.0625
